version: '3'

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins    
    networks:
      - jenkinsnet
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - ./volume/jenkins:/var/jenkins_home
      - ./volume/var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"

networks:
  jenkinsnet:
    driver: bridge
